"""
Day 4 — Tool Use (function calling) with the Anthropic API.

Run it:
    python3 day04-tool-use.py

Goal: define a tool, run the request → tool_use → tool_result loop.
"""

import os
import json
from anthropic import Anthropic

client = Anthropic()

# ----- Tool definition -----
TOOLS = [
    {
        "name": "get_campaign_status",
        "description": "Returns the current status and spend for a named marketing campaign.",
        "input_schema": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "The name of the campaign to look up."
                }
            },
            "required": ["name"]
        }
    },
    {
        "name": "get_campaign_leads",
        "description": "Returns the number of leads generated by a named marketing campaign.",
        "input_schema": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "description": "The name of the campaign to look up."
                }
            },
            "required": ["name"]
        }
    }
]

# ----- Stub functions (fake data) -----
def get_campaign_status(name: str) -> dict:
    campaigns = {
        "spring launch":  {"name": name, "status": "live", "spend": 42000},
        "q3 nurture":    {"name": name, "status": "paused", "spend": 1850},
    }
    return campaigns.get(name.lower(), {"name": name, "status": "not found", "spend": 0})

def get_campaign_leads(name: str) -> dict:
    campaigns = {
        "spring launch": {"name": name, "leads": 312},
        "q3 nurture":    {"name": name, "leads": 87},
    }
    return campaigns.get(name.lower(), {"name": name, "leads": 0})

def call_tool(tool_name: str, tool_input: dict) -> str:
    if tool_name == "get_campaign_status":
        result = get_campaign_status(tool_input["name"])
    elif tool_name == "get_campaign_leads":
        result = get_campaign_leads(tool_input["name"])
    else:
        result = {"error": f"Unknown tool: {tool_name}"}
    return json.dumps(result)


def run_tool_loop(user_message: str):
    print(f"\n{'='*60}")
    print(f"User: {user_message}")
    print('='*60)

    messages = [{"role": "user", "content": user_message}]

    # First API call — model may request a tool
    response = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=512,
        tools=TOOLS,
        messages=messages,
    )

    print(f"\nStop reason: {response.stop_reason}")

    # Tool-use loop
    while response.stop_reason == "tool_use":
        # Find the tool_use block(s)
        tool_use_block = next(b for b in response.content if b.type == "tool_use")
        tool_name  = tool_use_block.name
        tool_input = tool_use_block.input
        tool_use_id = tool_use_block.id

        print(f"\n→ Model called: {tool_name}({tool_input})")

        # Call the stub
        tool_result = call_tool(tool_name, tool_input)
        print(f"← Stub returned: {tool_result}")

        # Append assistant turn + tool result, then call again
        messages.append({"role": "assistant", "content": response.content})
        messages.append({
            "role": "user",
            "content": [
                {
                    "type": "tool_result",
                    "tool_use_id": tool_use_id,
                    "content": tool_result,
                }
            ]
        })

        response = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=512,
            tools=TOOLS,
            messages=messages,
        )
        print(f"\nStop reason: {response.stop_reason}")

    # Final natural-language answer
    final = "".join(b.text for b in response.content if b.type == "text")
    print(f"\nModel: {final}")


def main():
    if not os.environ.get("ANTHROPIC_API_KEY"):
        raise SystemExit("Set ANTHROPIC_API_KEY first.")

    # Triggers get_campaign_status
    run_tool_loop("What's the status of the Spring Launch campaign?")

    # Triggers get_campaign_leads
    run_tool_loop("How many leads did the Q3 Nurture campaign generate?")


if __name__ == "__main__":
    main()
